#ifndef FLECS_ENGINE_GEOMETRY_PRIMITIVES3_H
#define FLECS_ENGINE_GEOMETRY_PRIMITIVES3_H

#undef ECS_META_IMPL
#ifndef FLECS_ENGINE_GEOMETRY_PRIMITIVES3_IMPL
#define ECS_META_IMPL EXTERN
#endif

ECS_STRUCT(FlecsCube, {
    int32_t size;
});

#endif
