#ifndef FLECS_ENGINE_TONY_MC_MAPFACE_LUT_H
#define FLECS_ENGINE_TONY_MC_MAPFACE_LUT_H

#include <stdint.h>

#define FLECS_ENGINE_TONY_MC_MAPFACE_LUT_WIDTH (48)
#define FLECS_ENGINE_TONY_MC_MAPFACE_LUT_HEIGHT (48)
#define FLECS_ENGINE_TONY_MC_MAPFACE_LUT_DEPTH (48)
#define FLECS_ENGINE_TONY_MC_MAPFACE_LUT_TEXEL_COUNT (110592)

extern const uint32_t flecs_engine_tony_mc_mapface_lut[FLECS_ENGINE_TONY_MC_MAPFACE_LUT_TEXEL_COUNT];

#endif
